//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAU.GCT.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitorComment()
        {
            this.ReplyComment = new HashSet<ReplyComment>();
            this.PublicInformation = new HashSet<PublicInformation>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<int> DelFlag { get; set; }
        public Nullable<int> RecoveryState { get; set; }
        public Nullable<System.DateTime> RecoveryTime { get; set; }
        public string RecoveryPeople { get; set; }
        public string Position { get; set; }
        public Nullable<int> VisitorId { get; set; }
        public Nullable<int> State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyComment> ReplyComment { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicInformation> PublicInformation { get; set; }
    }
}
